version: '3.7'

services:
  web-pass-app:
    image: nginx:stable-alpine3.19-slim
    container_name: web-pass-app
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true
